### ISSUE TITLE
0.8.0 development roadmap: addressing ROpenSci review

### ISSUE THREAD

**Issue by sigmafelix** [ropensci/chopin#85]
## Main functions
- [x] Two parallel backends: `future` and `mirai`
- [x] Rename `par_group_grid`
- [x] `extract_at` as the only function for extract raster values at generic polygons
- [x] Recheck examples of wrapper functions
- [x] Toy examples or make the current examples smaller
- [x] `par_cut_coords`: add `sf::st_zm(drop = TRUE)`
- [x] `extract_at_poly`: `st_crs(polys) == st_crs(surf)` -> `extract_at` preprocesses CRS. Still having issues with nonexisting CRS.
- [x] CRS handling for all input classes (i.e., character inputs)
- [x] Elegant way of argument injection in `par_grid`, `par_hierarchy`, and `par_multiraters`, i.e., avoiding positional arguments
  - [x] Use generic argument names `x` and `y` in favor of `sf`/`terra` conventions
- [ ] ➡️ seamless `tar_target` integration: return WKT/WKB list to branch out
  - [x] Test branching WKT vs `sf` objects ... the other argument in `extract_at` or parallelizable piece of `chopin` and others' functions?
  - ~~[ ] Hierarchy case: truly nested vs different hierarchy across branch -- spin off a hierarchy definition function from `par_hierarchy` where takes a simple hierarchy object like the output of `par_make_gridset`~~

## Auxiliary/internal functions
- [x] Do not export aux functions
- [x] `dep_switch`: add potential use cases, narrow the scope
  - [x] documentation: supported object types in `sf` and `terra`
- [x] Verbosity control for debugging and being explicit about intermediate spatial data manipulation steps (i.e., reprojection, extent setting, etc.)

## Documentation
- [x] Clear distinction between `summarize_aw` (vector-vector) and `extract_at_buffer_kernel` (vector-raster)
- [x] Move 2D geometries caveats to the later part of README
- [x] Multiple point of entry: add quick start code snippets in README, introductory vignettes, and package documentation
- [x] Remove acronym from DESCRIPTION and consider more generalized package title
- [x] Flowchart
  - [x] Split into clearly separate plots
  - [x] Add explicit elaboration of the plots in README
- [ ] Reorganize vignettes
  - [ ] Benchmark cases into a separate vignette
  - [x] Extend HPC vignettes
- [x] Change default `future::plan` to `future::multisession`
  - [x] Internally convert terra input to sf if `multisession` is detected ([#82](https://github.com/NIEHS/chopin/issues/82))
- [x] Precomputing: fix broken figure paths
- [x] Clarify inexhaustive grid in `par_group_balanced` documentation
- [ ] Add justification to all default argument values
- [x] Fix URLs (to internal and external functions as well as internet links)
- [x] Add `CITATION` file
  - [x] `CITATION.cff` to .Rbuildignore
  - [ ] #93
- [x] Remove `To run this example`
- [x] Clarification of the concept of SEDC in `summarize_sedc`

## Programming practices
- [x] Standard S3 practices for switching functions
- [x] Add expected values in `expect_message`
- [x] Reduce the number of `expect_no_error`
- [x] Avoid single long tests
- [x] Legibility of package loading codes: use `library`
- [x] Community guidelines (i.e., `CONTRIBUTING.md`)
- [x] Codemetar synchronization (cf. [link](https://github.com/ropensci/codemetar?tab=readme-ov-file#keep-codemetajson-up-to-date))
- [x] Standard messaging functions instead of `cat` or `print`
- [x] `inherits()` rather than using `grepl()` at `class()` outputs
- [x] Add tests for different operating systems

## Exploration
- [ ] `wk` dependency for lightweight branching
  - [ ] Performance comparison

**Comment by sigmafelix** [comment]
https://github.com/NIEHS/chopin/commit/9d89ead6032eced4a57bcb1438d206f5f278133a

**Comment by sigmafelix** [comment]
For `dep_switch` task, `dep_switch` is set internal now. Developer's guide on this function might be useful, but I think it is very obvious what it does and its utility in other `chopin` functions.

**Comment by sigmafelix** [comment]
Tests for different OSes: `skip_on_os()` is added when `plan::multicore()` is applied (i.e., terra-terra inputs). I recall that CI on Windows workers failed with strange `mirai` related behaviors that were not reproduced in my Windows laptop (on bare R 4.4.1). I will keep track on this issue.

**Comment by sigmafelix** [comment]
`chopin` is approved. Before transferring the repository to ropensci, pre-transfer task list is here: https://github.com/ropensci/software-review/issues/638#issuecomment-2371130935

**Comment by sigmafelix** [comment]
- [ ] Transfer the repo to rOpenSci's "ropensci" GitHub organization under "Settings" in your repo. I have invited you to a team that should allow you to do so. You will need to [enable two-factor authentication](https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/configuring-two-factor-authentication) for your GitHub account.

- [ ] This invitation will expire after one week. If it happens write a comment @ropensci-review-bot invite me to ropensci/<package-name> which will re-send an invitation.
 After transfer write a comment @ropensci-review-bot finalize transfer of <package-name> where <package-name> is the repo/package name. This will give you admin access back.
- [ ] Fix all links to the GitHub repo to point to the repo under the ropensci organization.
- [ ] Delete your current code of conduct file if you had one since rOpenSci's default one will apply, see https://devguide.ropensci.org/collaboration.html#coc-file
- [ ] If you already had a pkgdown website and are ok relying only on [rOpenSci central docs building and branding](https://devguide.ropensci.org/ci.html#even-more-ci-ropensci-docs),
deactivate the automatic deployment you might have set up
- [ ] remove styling tweaks from your pkgdown config but keep that config file
replace the whole current pkgdown website with a [redirecting page](https://devguide.ropensci.org/redirect.html)
replace your package docs URL with https://docs.ropensci.org/package_name
- [ ] In addition, in your DESCRIPTION file, include the docs link in the URL field alongside the link to the GitHub repository, e.g.: URL: https://docs.ropensci.org/foobar, https://github.com/ropensci/foobar
- [ ] Skim the docs of the [pkgdown automatic deployment](https://devguide.ropensci.org/building.html#docsropensci), in particular if your website needs MathJax.
- [ ]  Fix any links in badges for CI and coverage to point to the new repository URL.
- [ ]  Increment the package version to reflect the changes you made during review. In NEWS.md, add a heading for the new version and one bullet for each user-facing change, and each developer-facing change that you think is relevant.
 We're starting to roll out software metadata files to all rOpenSci packages via the Codemeta initiative, see https://docs.ropensci.org/codemetar/ for how to include it in your package, after installing the package - should be easy as running codemetar::write_codemeta() in the root of your package.
- [ ] You can add this installation method to your package README install.packages("<package-name>", repos = "https://ropensci.r-universe.dev") thanks to [R-universe](https://ropensci.org/blog/2021/06/22/setup-runiverse/).
